version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend-api
      - backend-ai
    networks:
      - app-network
    volumes:
      - ./frontend/cs:/app

  backend-api:
    build:
      context: .
      dockerfile: docker/backend-api.Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./backend-api:/app

  backend-ai:
    build:
      context: .
      dockerfile: docker/backend-ai.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend-ai:/app

networks:
  app-network:
    driver: bridge
